- name: Initialize Docker Swarm
  hosts: all
  become: yes
  tasks:
  - name: Initialize Docker Swarm
    shell: |
      (docker info | grep -q 'Swarm: active' ) || docker swarm init --advertise-addr 192.168.100.202
    become: true
    tags: swarm
